# Use an official Python runtime as a parent image
FROM python:3.8-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Add current directory code to working directory in container
ADD . /app

# Install system libraries
RUN apt-get update && apt-get install -y \
    python3-dev \
    gcc \
    g++ \
    curl \
    wget \
    unzip \
    && apt-get clean

# Install chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install

# Copy the requirements.txt alone to leverage Docker cache
COPY requirements.txt ./requirements.txt

# Install python packages
RUN pip3 install --upgrade pip -r requirements.txt

# Install python packages from packages.txt if it exists
COPY packages.txt ./packages.txt
RUN if [ -f packages.txt ]; then pip3 install --upgrade pip -r packages.txt; fi

# Run streamlit on container start
CMD streamlit run app.py
